projects:
  # tracktrace-api:
  #   schemaPath: src/generated/tracktrace-api.graphql
  #   extensions:
  #     prisma: database/tracktrace-api/prisma.yml
  #     codegen:
  #       - generator: prisma-binding
  #         language: javascript
  #         output:
  #           binding: src/generated/tracktrace-api.js
  authorizationApi:
    schemaPath: src/generated/authorizationApi.graphql
    extensions:
      prisma: database/authorizationApi/prisma.yml
      codegen:
        - generator: prisma-binding
          language: javascript
          output:
            binding: src/generated/authorizationApi.js
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoint:
        default: http://localhost:4000
