projects:
  tracktrace-api:
    schemaPath: src/generated/tracktrace-api.graphql
    extensions:
      prisma: database/tracktrace-api/prisma.yml
      codegen:
        - generator: prisma-binding
          language: javascript
          output:
            binding: src/generated/tracktrace-api.js
  authorization-api:
    schemaPath: src/generated/authorization-api.graphql
    extensions:
      prisma: database/authorization-api/prisma.yml
      codegen:
        - generator: prisma-binding
          language: javascript
          output:
            binding: src/generated/authorization-api.js
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
default: http://localhost:4000