version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            database: TrackTrace
            migrations: true
            rawAccess: true
  postgres:
    image: postgres
    restart: "unless-stopped"
    hostname: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      PG_DATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: "unless-stopped"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@4ls.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  ? postgres
  ? pgadmin
